In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

## Series

In [2]:
obj = pd.Series([-9,2,0,-4])
obj

0   -9
1    2
2    0
3   -4
dtype: int64

In [3]:
obj.values

array([-9,  2,  0, -4], dtype=int64)

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([-9,  2,  0, -4], index=['a','b','c','d'])

In [9]:
obj2

a   -9
b    2
c    0
d   -4
dtype: int64

In [10]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [11]:
obj2['a']

-9

In [12]:
obj2['a'] = -99
obj2

a   -99
b     2
c     0
d    -4
dtype: int64

In [13]:
obj2[['c', 'a', 'd']]

c     0
a   -99
d    -4
dtype: int64

In [17]:
np.max(obj2)

2

In [20]:
'b' in obj2

True

#### Should you have data contained in a Python dict, you can create a Series from it by passing the dict:

In [2]:
sdata = {'Ohio': 35000, 'Texas': [2,3.3,'Hello'], 2: [-9999,'Utah'], 'Utah': 5000}
sdata = pd.Series(sdata)

In [36]:
sdata['Texas'][2]

'Hello'

In [37]:
pd.isnull(obj2)

state
a    False
b    False
c    False
d    False
Name: Population, dtype: bool

In [38]:
pd.notnull(obj2)

state
a    True
b    True
c    True
d    True
Name: Population, dtype: bool

In [39]:
sdata.name = "Population"

In [40]:
sdata.index.name = 'state'
sdata

state
Ohio               35000
Texas    [2, 3.3, Hello]
2          [-9999, Utah]
Utah                5000
Name: Population, dtype: object

In [41]:
sdata.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [42]:
sdata

Bob                35000
Steve    [2, 3.3, Hello]
Jeff       [-9999, Utah]
Ryan                5000
Name: Population, dtype: object

## DataFrame

#### There are many ways to construct a DataFrame, though one of the most common is from a dict of equal-length lists or NumPy arrays:

In [4]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [5]:
df = pd.DataFrame(data)
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

## Check Class Imbalance

In [11]:
df['year'].value_counts()

2002    2
2001    2
2003    1
2000    1
Name: year, dtype: int64

In [45]:
df.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [70]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [71]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])

In [72]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [51]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [52]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [53]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [54]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [62]:
frame2.loc["three"]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [63]:
frame2['debt'] = 16.5

In [64]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [65]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [74]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [75]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [78]:
del frame2['eastern']

In [79]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [80]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [88]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [84]:
df3 = pd.DataFrame(pop)
df3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [85]:
df3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [90]:
df3.index=[2001, 2002, 2003]
df3

Nevada  Ohio
2001     NaN   1.5
2002     2.4   1.7
2003     2.9   3.6

In [103]:
df3[-1:]

Nevada  Ohio
2003     2.9   3.6

In [106]:
df3[:-1] # or df3[:2]

Nevada  Ohio
2001     NaN   1.5
2002     2.4   1.7

In [107]:
np.array(df3)

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [108]:
df3.index.name = 'year'; df3.columns.name = 'state'

In [109]:
df3

state  Nevada  Ohio
year               
2001      NaN   1.5
2002      2.4   1.7
2003      2.9   3.6

In [110]:
df3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])